networks:
  app-network:
    driver: bridge

volumes:
  images:
  logs:
  postgres_data:

services:
  app:
    container_name: app
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - images:/app/images
      - logs:/app/logs
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure:5

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env  # Все переменные берутся отсюда
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: on-failure:5

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - images:/images
      - ./static:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - app
    restart: on-failure:5