services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - images:/app/images
      - logs:/app/logs

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - images:/var/www/images
    depends_on:
      - app

volumes:
  images:
  logs: